name : "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Store Repositories
          uses: actions/checkout@v3

        - name: Set Up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.35.3'
            channel : 'stable'

        - name: Paketlarni o'rnatish
          run: flutter pub get

        - name: Testlarni ishga tushirish
          run: flutter test